# config.yaml
paths:
  train_images: "C:/Users/Kevin/Clustererkennung/bolt_detection/dataset/images/train"
  val_images: "C:/Users/Kevin/Clustererkennung/bolt_detection/dataset/images/val"
  train_labels: "C:/Users/Kevin/Clustererkennung/bolt_detection/dataset/labels/train"
  val_labels: "C:/Users/Kevin/Clustererkennung/bolt_detection/dataset/labels/val"
  yolo_inference: "C:/Users/Kevin/Clustererkennung/bolt_detection/scripts/Cluster/Outputs/inference/run_v7_robust_noscaling"
  cluster_model: "C:/Users/Kevin/Clustererkennung/bolt_detection/scripts/Cluster/Outputs/models/2000_cluster.pkl"
  output_root: "C:/Users/Kevin/Clustererkennung/bolt_detection/scripts/GNN/outputs"

gnn:
  input_features: 2  # x, y
  hidden_dim: 32
  output_dim: 2      # Autoencoder sollte Eingabe rekonstruieren
  num_layers: 3
  k_neighbors: 7     # Für k-NN Graph-Erstellung. Bei kleinen, dichten Objekten hilft ein etwas kleinerer Wert, den lokalen Kontext präzise zu erfassen.

training:
  run_name: "training_Cluster_1" # Name für diese Trainingssitzung. Das Modell wird in einem Ordner mit diesem Namen gespeichert.
  epochs: 150
  batch_size: 1
  lr: 0.001

inference:
  training_run_to_use: "training_Cluster_1" # Welches trainierte Modell soll für die Inferenz verwendet werden (Name des Trainingslauf-Ordners).
  run_name: "hybrid_filter_run_1" # Name für diese Validierungssitzung. Ausgaben werden in einem Ordner mit diesem Namen gespeichert.
  # yolo_confidence_threshold ist in der neuen Logik veraltet. Die Filterung basiert auf Klasse 1 (Kandidat).
  anomaly_threshold: 0.615        # Rekonstruktionsfehler-Schwelle. Ein Punkt wird als Anomalie entfernt, wenn der GNN ihn um mehr als diesen Wert (in normalisierten Koordinaten) verschieben möchte. Dieser Wert ist ein guter Startpunkt für kleine Schrauben.

evaluation:
  iou_threshold: 0.5 # IoU-Schwellenwert, um zu bestimmen, ob eine vorhergesagte Box mit einer Ground-Truth-Box übereinstimmt.

visualization:
  line_thickness: 2
  removed_box_color: [0, 0, 255] # Rot in BGR
  kept_box_color: [0, 255, 0]    # Grün in BGR
